In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv("train.csv")
train_data.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,year,Release Clause,DefensiveAwareness
0,0,195427,J. Stockley,22,https://cdn.sofifa.com/players/195/427/17_60.png,England,https://cdn.sofifa.com/flags/gb-eng.png,61,68,Aberdeen,...,14.0,6.0,15.0,9.0,12.0,ST,60.0,2017,NaN,NaN
1,1,203539,K. Devaney,25,https://cdn.sofifa.com/players/203/539/17_60.png,Republic of Ireland,https://cdn.sofifa.com/flags/ie.png,57,58,Galway United,...,6.0,12.0,13.0,12.0,10.0,RM,57.0,2017,NaN,NaN
2,2,232898,T. Morishima,23,https://cdn.sofifa.com/players/232/898/20_60.png,Japan,https://cdn.sofifa.com/flags/jp.png,71,76,Sanfrecce Hiroshima,...,13.0,15.0,6.0,15.0,6.0,CAM,74.0,2021,€4.2M,32.0
3,3,215502,B. Drągowski,18,https://cdn.sofifa.com/players/215/502/17_60.png,Poland,https://cdn.sofifa.com/flags/pl.png,71,86,Fiorentina,...,68.0,68.0,70.0,71.0,74.0,GK,70.0,2017,NaN,NaN
4,4,222263,N. Jackers,19,https://cdn.sofifa.com/players/222/263/18_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,64,75,KRC Genk,...,65.0,64.0,59.0,60.0,65.0,GK,63.0,2018,€978K,NaN

In [3]:
Y = train_data[['Value']]
Y

       Value
0      €325K
1      €140K
2      €3.2M
3      €2.9M
4      €575K
...      ...
87637  €950K
87638  €100K
87639  €1.1M
87640  €875K
87641  €775K

[87642 rows x 1 columns]

In [4]:
# checking for null values 
null_count = Y.isnull().sum()
null_count

# NO NULL values

Value    0
dtype: int64

# Problem Identified -- Regression

In [5]:

# Listing down all the column names in the text file 
column_names = train_data.columns.tolist()

with open('output_file.txt', 'w') as file:
    file.write('\n'.join(column_names))

In [6]:
# Dropping the values 

import pandas as pd

# Assuming you have a DataFrame called 'df' containing the dataset

# List of columns to be removed
columns_to_remove = ['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Club', 'Club Logo', 'Wage', 'Special']

# Drop the columns from the DataFrame
df = train_data.drop(columns=columns_to_remove)

In [7]:
df.shape

train = df

In [8]:
import pandas as pd

# Assuming you have a dataset in a pandas DataFrame called 'data'
# and you want to check for null values and fill them with standard values.

# Check for null values in the dataset
null_values = train.isnull().sum()/len(train) * 100
print("Null Values:")
print(null_values)

Null Values:
Overall                      0.000000
Potential                    0.000000
Value                        0.000000
Preferred Foot               0.000000
International Reputation     0.000000
Weak Foot                    0.000000
Skill Moves                  0.000000
Work Rate                    0.000000
Body Type                    0.059332
Real Face                    0.059332
Position                     0.103831
Jersey Number                0.103831
Joined                      10.210858
Loaned From                 92.342712
Contract Valid Until         2.493097
Height                       0.000000
Weight                       0.000000
Crossing                     0.000000
Finishing                    0.000000
HeadingAccuracy              0.000000
ShortPassing                 0.000000
Volleys                      0.088998
Dribbling                    0.000000
Curve                        0.088998
FKAccuracy                   0.000000
LongPassing                  0.000000
BallControl                  0.000000
Acceleration                 0.000000
SprintSpeed                  0.000000
Agility                      0.088998
Reactions                    0.000000
Balance                      0.088998
ShotPower                    0.000000
Jumping                      0.088998
Stamina                      0.000000
Strength                     0.000000
LongShots                    0.000000
Aggression                   0.000000
Interceptions                0.007987
Positioning                  0.007987
Vision                       0.088998
Penalties                    0.000000
Composure                    0.806691
Marking                     36.037516
StandingTackle               0.000000
SlidingTackle                0.088998
GKDiving                     0.000000
GKHandling                   0.000000
GKKicking                    0.000000
GKPositioning                0.000000
GKReflexes                   0.000000
Best Position                0.000000
Best Overall Rating          0.000000
year                         0.000000
Release Clause              28.633532
DefensiveAwareness          63.962484
dtype: float64

In [9]:
# removing the columns with max null values 
columns_to_remove = ['Release Clause','DefensiveAwareness','Loaned From']
df = train_data.drop(columns=columns_to_remove)
df.shape

(87642, 64)

In [10]:
import pandas as pd

# Assuming you have a dataset in a pandas DataFrame called 'data'
# and you want to check for null values and fill them with standard values.

# Check for null values in the dataset
null_values = df.isnull().sum()/len(train) * 100
print("Null Values:")
print(null_values)

Null Values:
Unnamed: 0             0.0
ID                     0.0
Name                   0.0
Age                    0.0
Photo                  0.0
                      ...
GKPositioning          0.0
GKReflexes             0.0
Best Position          0.0
Best Overall Rating    0.0
year                   0.0
Length: 64, dtype: float64

In [11]:
# Custom conversion function
def convert_value(entry):
    entry = entry.str.replace("€", "")  # Remove the euro sign
    
    mask_k = entry.str.contains("K")
    mask_m = entry.str.contains("M")
    
    entry_k = entry[mask_k].str.replace("K", "").astype(float) * 1000
    entry_m = entry[mask_m].str.replace("M", "").astype(float) * 1000000
    
    entry[mask_k] = entry_k
    entry[mask_m] = entry_m
    
    return entry.astype(float)

# Apply the conversion function to the 'Value' column
df['Value'] = convert_value(df['Value'])

In [12]:
Y = df['Value']
Y

0         325000.0
1         140000.0
2        3200000.0
3        2900000.0
4         575000.0
           ...
87637     950000.0
87638     100000.0
87639    1100000.0
87640     875000.0
87641     775000.0
Name: Value, Length: 87642, dtype: float64

In [13]:
import pandas as pd

# Assuming you have a dataset in a pandas DataFrame called 'data'
# and you want to check the number of null values in each column.

# Check the number of null values in each column
null_counts = df.isnull().sum()/len(df)*100

# Save null value counts to a text file
null_counts.to_csv("null_percentage.txt", header=False)

print("Null value counts saved to 'null_percentage.txt'")

Null value counts saved to 'null_percentage.txt'

In [14]:
df

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,year
0,0,195427,J. Stockley,22,https://cdn.sofifa.com/players/195/427/17_60.png,England,https://cdn.sofifa.com/flags/gb-eng.png,61,68,Aberdeen,...,25.0,18.0,14.0,6.0,15.0,9.0,12.0,ST,60.0,2017
1,1,203539,K. Devaney,25,https://cdn.sofifa.com/players/203/539/17_60.png,Republic of Ireland,https://cdn.sofifa.com/flags/ie.png,57,58,Galway United,...,38.0,37.0,6.0,12.0,13.0,12.0,10.0,RM,57.0,2017
2,2,232898,T. Morishima,23,https://cdn.sofifa.com/players/232/898/20_60.png,Japan,https://cdn.sofifa.com/flags/jp.png,71,76,Sanfrecce Hiroshima,...,36.0,31.0,13.0,15.0,6.0,15.0,6.0,CAM,74.0,2021
3,3,215502,B. Drągowski,18,https://cdn.sofifa.com/players/215/502/17_60.png,Poland,https://cdn.sofifa.com/flags/pl.png,71,86,Fiorentina,...,16.0,16.0,68.0,68.0,70.0,71.0,74.0,GK,70.0,2017
4,4,222263,N. Jackers,19,https://cdn.sofifa.com/players/222/263/18_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,64,75,KRC Genk,...,15.0,12.0,65.0,64.0,59.0,60.0,65.0,GK,63.0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87637,87637,188278,M. Birighitti,25,https://cdn.sofifa.com/players/188/278/17_60.png,Australia,https://cdn.sofifa.com/flags/au.png,68,73,Swansea City,...,14.0,14.0,70.0,65.0,64.0,67.0,73.0,GK,67.0,2017
87638,87638,239649,D. Marino,28,https://cdn.sofifa.com/players/239/649/18_60.png,Italy,https://cdn.sofifa.com/flags/it.png,58,58,Ternana,...,62.0,61.0,7.0,7.0,12.0,7.0,9.0,CB,57.0,2018
87639,87639,258958,O. Filippov,27,https://cdn.sofifa.com/players/258/958/20_60.png,Ukraine,https://cdn.sofifa.com/flags/ua.png,69,69,Sint-Truidense VV,...,18.0,16.0,6.0,9.0,5.0,9.0,8.0,ST,69.0,2021
87640,87640,240097,F. Downes,20,https://cdn.sofifa.com/players/240/097/20_60.png,England,https://cdn.sofifa.com/flags/gb-eng.png,66,72,Ipswich Town,...,72.0,69.0,13.0,12.0,14.0,11.0,6.0,CDM,70.0,2020
87641,87641,219527,C. Mafla,26,https://cdn.sofifa.com/players/219/527/20_60.png,Colombia,https://cdn.sofifa.com/flags/co.png,67,68,Atlético Nacional,...,68.0,71.0,7.0,15.0,11.0,8.0,13.0,LB,67.0,2020

In [15]:

# List of columns to be removed
columns_to_remove = ['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Club', 'Club Logo', 'Wage', 'Special']

# Drop the columns from the DataFrame
df = df.drop(columns=columns_to_remove)

In [16]:
df.shape

(87642, 53)

In [17]:
import pandas as pd

# Assuming you have a dataset in a pandas DataFrame called 'data'
# and you want to check the number of null values in each column.

# Check the number of null values in each column
null_counts = df.isnull().sum()/len(df)*100

# Save null value counts to a text file
null_counts.to_csv("null_percentage.txt", header=False)

print("Null value counts saved to 'null_percentage.txt'")

Null value counts saved to 'null_percentage.txt'

In [18]:
Y

0         325000.0
1         140000.0
2        3200000.0
3        2900000.0
4         575000.0
           ...
87637     950000.0
87638     100000.0
87639    1100000.0
87640     875000.0
87641     775000.0
Name: Value, Length: 87642, dtype: float64

In [19]:

# List of columns to be removed
columns_to_remove = ['Marking','Composure','Joined']

# Drop the columns from the DataFrame
df = df.drop(columns=columns_to_remove)

In [20]:


# List of columns to be removed
columns_to_remove = ['Value']

# Drop the columns from the DataFrame
X = df.drop(columns=columns_to_remove)
X.shape

import pandas as pd


# Find the most commonly occurring foot
most_common_foot = df['Preferred Foot'].mode().values[0]

# Fill missing values with the most commonly occurring foot
X['Preferred Foot'].fillna(most_common_foot, inplace=True)

X['Preferred Foot']

from sklearn.preprocessing import LabelEncoder

# Assuming you have a dataset in a pandas DataFrame called 'df'
# and you want to label encode the 'Preferred Foot' column.

# Perform label encoding
le = LabelEncoder()
X['Preferred Foot'] = le.fit_transform(df['Preferred Foot'])

In [21]:

# List of columns to be removed
columns_to_remove = ['Contract Valid Until','Work Rate','Real Face','Position','Jersey Number','Best Position']

# Drop the columns from the DataFrame
X = X.drop(columns=columns_to_remove)

In [22]:
X['Body Type'] = X['Body Type'].str.split('(').str[0]

In [23]:
# Perform label encoding
le = LabelEncoder()
X['Body Type'] = le.fit_transform(X['Body Type'])

In [24]:


X['Weight'] = X['Weight'].str.replace('lbs', '')

In [25]:
import pandas as pd

# Assuming you have a dataset in a pandas DataFrame called 'df'
# and you want to convert the 'Height' column from foot to centimeters.

# Define a conversion function
def convert_height(height):
    parts = height.split("'")  # Split the height value by the foot symbol
    feet = int(parts[0])  # Extract the feet part as an integer
    inches = int(parts[1])  # Extract the inches part as an integer
    total_inches = (feet * 12) + inches  # Calculate the total height in inches
    cm = total_inches * 2.54  # Convert inches to centimeters
    return cm

In [26]:

# Apply the conversion function to the 'Height' column
X['Height'] = X['Height'].apply(convert_height)

In [27]:
X.to_csv('X.csv',index = False)

In [28]:
# Final Checking 
import pandas as pd

# Assuming you have a dataset in a pandas DataFrame called 'data'
# and you want to check the number of null values in each column.

# Check the number of null values in each column
null_counts = X.isnull().sum()/len(df)*100

# Save null value counts to a text file
null_counts.to_csv("null_percentage.txt", header=False)

print("Null value counts saved to 'null_percentage.txt'")

Null value counts saved to 'null_percentage.txt'

In [29]:

# List of columns to be removed
columns_to_remove = ['year']

# Drop the columns from the DataFrame
X = X.drop(columns=columns_to_remove)

In [30]:
import pandas as pd
import numpy as np

# Assuming you have a dataset in a pandas DataFrame called 'df'
# and you want to fill the null values in the 'Volleys' column.

# Fill null values with mean
mean_value = X['Volleys'].mean()
X['Volleys'].fillna(mean_value, inplace=True)

# Alternatively, fill null values with median
median_value = df['Volleys'].median()
X['Volleys'].fillna(median_value, inplace=True)

In [31]:
import numpy as np

# Assuming you have a dataset in a pandas DataFrame called 'df'
# and you want to fill the null values in the 'Volleys' column.

# Fill null values with mean
mean_value = X['Curve'].mean()
X['Curve'].fillna(mean_value, inplace=True)

# Alternatively, fill null values with median
median_value = df['Curve'].median()
X['Curve'].fillna(median_value, inplace=True)

In [32]:
import pandas as pd
import numpy as np

# Assuming you have a dataset in a pandas DataFrame called 'df'
# and you want to fill the null values in the 'Curve' and 'Agility' columns.

# Fill null values in 'Curve' column with mean
mean_curve = X['Curve'].mean()
X['Curve'].fillna(mean_curve, inplace=True)

# Fill null values in 'Agility' column with average
average_agility = X['Agility'].mean()
X['Agility'].fillna(average_agility, inplace=True)

In [33]:
import pandas as pd
import numpy as np

# Assuming you have a dataset in a pandas DataFrame called 'df'

# List of column names
columns = ['Interceptions', 'Balance', 'Jumping','SlidingTackle','Vision','Positioning']

# Iterate over each column in the list
for column in columns:
    # Calculate the mean value of the column
    mean_value = X[column].mean()
    # Fill the null values in the column with the mean value
    X[column].fillna(mean_value, inplace=True)

In [34]:
X_train = X

In [35]:
X_train.to_csv('X_train.csv',index = False)

In [39]:
Y.to_csv("Y_train.csv")